#!/usr/bin/env bash
#
# call me to start the show

echo 'setting up computer...'

# Check for Homebrew
if test ! $(which brew)
then
  echo '  Installing x-code for you.'
  xcode-select --install
  echo "  Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
echo '  Installing brew cmd utils...'
brew install node

echo '  Installing brew-cask and gui apps...'
brew install caskroom/cask/brew-cask
# general apps
brew cask install google-chrome	
brew cask install gimp

# source control apps
brew cask install github
brew cask install sourcetree

# dev apps
brew cask install atom
# brew cask install caskroom/homebrew-versions/java6
# brew cask install intellij-idea

# personal
# brew cask install plex-home-theater

echo 'setting up osx preferences...'
# set a shorter Delay until key repeat
defaults write NSGlobalDomain InitialKeyRepeat -int 12

# Bottom left screen corner → Start screen saver
defaults write com.apple.dock wvous-bl-corner -int 5
defaults write com.apple.dock wvous-bl-modifier -int 0

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

echo 'all done fool!'
